apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
      - name: genai-service
        image: ${DOCKER_HUB_USERNAME}/petclinic-genai-service:${TAG}
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: petclinic
spec:
  selector:
    app: genai-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP
