{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "petclinic.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "petclinic.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .port }}
{{- end }}